/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedEmailGeneratorRouteImport } from './routes/_authenticated/email-generator'
import { Route as AuthenticatedMeetingSummarizerRouteImport } from './routes/_authenticated/meeting-summarizer'
import { Route as AuthenticatedResearchAssistantRouteImport } from './routes/_authenticated/research-assistant'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTaskPlannerRouteImport } from './routes/_authenticated/task-planner'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailGeneratorRoute =
  AuthenticatedEmailGeneratorRouteImport.update({
    id: '/email-generator',
    path: '/email-generator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeetingSummarizerRoute =
  AuthenticatedMeetingSummarizerRouteImport.update({
    id: '/meeting-summarizer',
    path: '/meeting-summarizer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResearchAssistantRoute =
  AuthenticatedResearchAssistantRouteImport.update({
    id: '/research-assistant',
    path: '/research-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaskPlannerRoute =
  AuthenticatedTaskPlannerRouteImport.update({
    id: '/task-planner',
    path: '/task-planner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/email-generator': typeof AuthenticatedEmailGeneratorRoute
  '/meeting-summarizer': typeof AuthenticatedMeetingSummarizerRoute
  '/research-assistant': typeof AuthenticatedResearchAssistantRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/task-planner': typeof AuthenticatedTaskPlannerRoute
}
export interface FileRoutesByTo {
  '/assistant': typeof AuthenticatedAssistantRoute
  '/email-generator': typeof AuthenticatedEmailGeneratorRoute
  '/meeting-summarizer': typeof AuthenticatedMeetingSummarizerRoute
  '/research-assistant': typeof AuthenticatedResearchAssistantRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/task-planner': typeof AuthenticatedTaskPlannerRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/email-generator': typeof AuthenticatedEmailGeneratorRoute
  '/_authenticated/meeting-summarizer': typeof AuthenticatedMeetingSummarizerRoute
  '/_authenticated/research-assistant': typeof AuthenticatedResearchAssistantRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/task-planner': typeof AuthenticatedTaskPlannerRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/email-generator'
    | '/meeting-summarizer'
    | '/research-assistant'
    | '/settings'
    | '/task-planner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assistant'
    | '/email-generator'
    | '/meeting-summarizer'
    | '/research-assistant'
    | '/settings'
    | '/task-planner'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/assistant'
    | '/_authenticated/email-generator'
    | '/_authenticated/meeting-summarizer'
    | '/_authenticated/research-assistant'
    | '/_authenticated/settings'
    | '/_authenticated/task-planner'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-generator': {
      id: '/_authenticated/email-generator'
      path: '/email-generator'
      fullPath: '/email-generator'
      preLoaderRoute: typeof AuthenticatedEmailGeneratorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meeting-summarizer': {
      id: '/_authenticated/meeting-summarizer'
      path: '/meeting-summarizer'
      fullPath: '/meeting-summarizer'
      preLoaderRoute: typeof AuthenticatedMeetingSummarizerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/research-assistant': {
      id: '/_authenticated/research-assistant'
      path: '/research-assistant'
      fullPath: '/research-assistant'
      preLoaderRoute: typeof AuthenticatedResearchAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/task-planner': {
      id: '/_authenticated/task-planner'
      path: '/task-planner'
      fullPath: '/task-planner'
      preLoaderRoute: typeof AuthenticatedTaskPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedEmailGeneratorRoute: typeof AuthenticatedEmailGeneratorRoute
  AuthenticatedMeetingSummarizerRoute: typeof AuthenticatedMeetingSummarizerRoute
  AuthenticatedResearchAssistantRoute: typeof AuthenticatedResearchAssistantRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTaskPlannerRoute: typeof AuthenticatedTaskPlannerRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedEmailGeneratorRoute: AuthenticatedEmailGeneratorRoute,
  AuthenticatedMeetingSummarizerRoute: AuthenticatedMeetingSummarizerRoute,
  AuthenticatedResearchAssistantRoute: AuthenticatedResearchAssistantRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTaskPlannerRoute: AuthenticatedTaskPlannerRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
